services:
  db:
    image: postgres:17
    container_name: hotel-db
    environment:
      POSTGRES_USER: hotel_dba
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: hotel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hotel_dba -d hotel"]
      interval: 2s
      retries: 10
 
  app:
    build: .
    container_name: hotel-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: hotel_dba
      DB_PASSWORD: 12345678
      DB_NAME: hotel
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
